### ISSUE TITLE
How do I determine the correct node to obtain table from

### ISSUE THREAD

**Issue by pssguy** [cpsievert/rdom#5]
In your vignette

```
rdom("https://www.datatables.net/examples/data_sources/js_array.html") %>%
  html_node("#example") %>% html_table()
```

On that page, I am having trouble finding #example using the selectorGadget

I can see in view source

```
$('#example').dataTable( {
    "data": dataSet,
    "columns": [
        { "title": "Engine" },
        { "title": "Browser" },
        { "title": "Platform" },
        { "title": "Version", "class": "center" },
        { "title": "Grade", "class": "center" }
    ]
} );
```

but will all other pages I have to scrape have the same basic structure?

**Comment by cpsievert** [comment]
I'm not sure why selectorGadget isn't helping here, but I can see it with "Inspect Element":

![screen shot 2015-06-13 at 3 36 08 pm](https://cloud.githubusercontent.com/assets/1365941/8145919/1631a56a-11e2-11e5-90fb-726867d2a15c.png)

This is a bad example. See the new README for a better one.

**Comment by pssguy** [comment]
Thanks . Obvious solution!
