### ISSUE TITLE
Killed 9 Mac

### ISSUE THREAD

**Issue by muschellij2** [cpsievert/rdom#8]
See https://github.com/eugene1g/phantomjs/releases and [SO page](http://stackoverflow.com/questions/28267809/phantomjs-getting-killed-9-for-anything-im-trying) for reference to Killed 9 failure of phantomjs on OS X Yosemite.

**Comment by cpsievert** [comment]
Thanks for reporting. The SO post doesn't mention it, but you could also use homebrew to build phantomjs from source:

```
brew install phantomjs
```

That's what I did from the very start, so I never noticed this problem. I also like using homebrew since I can switch between versions easily:

```
brew switch phantomjs 1.9.8
brew switch phantomjs 2.0.0
```
